# Generated by Django 5.1.1 on 2024-09-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='tool',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
