# Generated by Django 5.1.1 on 2024-09-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tool_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
