# Generated by Django 5.1.1 on 2024-09-29 20:21

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_mymanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyManager',
        ),
        migrations.AlterModelManagers(
            name='tool',
            managers=[
                ('deactive_tools', django.db.models.manager.Manager()),
            ],
        ),
    ]
